name: Hexo Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Blog Branche
        uses: actions/checkout@v2
        with: 
          ref: Blog
      - name: Install Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Set Git Config
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'zpengg'
          git config --global user.email 'zpengg@yeah.net'
      - name: Install Hexo
        run: |
          npm i -g hexo-cli 
          npm i
      - name: Deploy Hexo
        run: |
          hexo g -d
